### ISSUE TITLE
Network mode support

### ISSUE THREAD

**Issue by meticulousunit** [calibrain/calibre-web-automated-book-downloader#116]
Is there a way to add support for the network_mode option in docker?
I am not an expert at all, but all my containers from the arr stack that need to download something go through the gleutun container which handles all the VPN traffic for this docker stack.

Using the default docker compose provided for the CWA Book Downloader works as intended, but when I try to add the "network_mode: service:gluetun" flag (or whatever this is called), I can't start the stack at all.

**Comment by meticulousunit** [comment]
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qbittorrent web interface
      - AAAAA:AAAAA# qbittorrent torrent port
      - AAAAA:AAAAA/udp # qbittorrent torrent port
      - 6789:6789 # nzbget
      - 9696:9696 # prowlarr
    volumes:
      - /docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=xxxxxxxx
      - VPN_TYPE=xxxxxxxx
      - FIREWALL_VPN_INPUT_PORTS=AAAAA
      - WIREGUARD_PRIVATE_KEY=xxxxxxxx
      - WIREGUARD_PRESHARED_KEY=xxxxxxxx
      - WIREGUARD_ADDRESSES=xxxxxxxx
      - SERVER_COUNTRIES=xxxxxxxx
      - SERVER_CITIES=xxxxxxxx
      - HEALTH_VPN_DURATION_INITIAL=xxxxxxxx
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 120s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  deunhealth:
    image: qmcgaw/deunhealth:latest
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=xxxxxxxx
      - TZ=xxxxxxxx
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy= "true"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=xxxxxxxx
      - WEBUI_PORT=8080
      - TORRENTING_PORT=AAAAA
    volumes:
      - /docker/qbittorrent:/config
      - /data:/data
    network_mode: service:gluetun
    healthcheck:
        test: ping -c 1 xxxxxxxx || exit 1
        interval: 120s
        retries: 5
        start_period: 20s
        timeout: 10s

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=xxxxxxxx
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/prowlarr:/config
    restart: unless-stopped
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989

....................................

  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=xxxxxxxx 
    volumes:
      - /docker/calibre-web-automated:/config 
      - /data/books/cwa-book-ingest:/cwa-book-ingest
      - /data/books/library:/calibre-library 
    ports:
      - 8083:8083 
    restart: unless-stopped
```

=================================
What I tried does not work if network_mode is set to "service:gluetun", but it does work with "none".

```
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      BOOK_LANGUAGE: en
      UID: 1000
      GID: 1000
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - /data/books/cwa-book-ingest:/cwa-book-ingest
    network_mode: service:gluetun
```

I went through all services running, and none of them use the same 8084 port.
When trying to update the stack in Portainer by just adding the calibre-web-automated-book-downloader at the end of the compose file, I only get the "stack can't be created" error. If I try to create the stack from scratch, I get this error:

```
Failed to deploy a stack: time="2025-04-04T14:20:09Z"
level=warning msg="/data/compose/2/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
Network servarr_default
Creating Network servarr_default
Created Container .......
.........................
Created Container gluetun
Created Container f3b1dc312348_nzbget
Recreate Container e344bf881aeb_prowlarr
Recreate Container e5e4cda65723_qbittorrent
Recreate Container f0f76c3d4030_api
Recreate Container servarr-calibre-web-automated-book-downloader-1
Creating Error response from daemon: conflicting options: port publishing and the container type network mode

```
