### ISSUE TITLE
'Error loading status. Will retry automatically.'

### ISSUE THREAD

**Issue by jpiscaer** [calibrain/calibre-web-automated-book-downloader#128]
Hi,

I have issues running CWABD in docker. I've been running it for a few weeks without issues (although I did use the separate cloudflarebypassforscraping docker image before; that seems no longer needed?), but after a reboot of the docker host, I cannot get it back to work. The error I get in the web app is 'An error occurred while searching. Please try again.' for the search and 'Error loading status. Will retry automatically.' for the download status. 

<img width="1224" alt="Image" src="https://github.com/user-attachments/assets/0f8feccf-5811-4d5a-ba10-368631e7294d" />

In the container logs, I can see:

`2025-04-14 09:29:57,951 - app - WARNING - app.py:235 - 404 error: http://localhost:8084/request/api/status : 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`

My docker compose is;

```
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: en,nl
      USE_BOOK_TITLE: true
      FLASK_DEBUG: false
      TZ: Europe/Amsterdam
      APP_ENV: prod
      UID: 1000
      GID: 100
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /my/own/folder:/cwa-book-ingest
```

I've tried the usual things, like reboot, removing the container and pruning docker system, checking whether the container can write to the /cwa-book-ingest folder, but I can't find a root cause for what's happening.. Note that I'm not running a calibre-web-automated instance at all, since I use calibre and calibre-web instead..
