### ISSUE TITLE
Cannot download (Session not created: error connection to chrome)

### ISSUE THREAD

**Issue by TomasGalvao** [calibrain/calibre-web-automated-book-downloader#130]
Hello,

Currently running the latest docker image.
I'm getting the following error while trying to download any book:

```
2025-04-14 20:55:53,029 - downloader - WARNING - downloader.py:57 - Exception while using cloudflare bypass for URL: https://annas-archive.org/slow_download/<....>

2025-04-14 20:55:53,029 - downloader - WARNING - downloader.py:58 - Exception: Message: session not created: cannot connect to chrome at 127.0.0.1:9222

from chrome not reachable
```
This is the _(one of multiple being spammed on the logs)_ stacktrace:
```
  File "/usr/local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3135, in get_driver

    return get_local_driver(

  File "/usr/local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 5186, in get_local_driver

    driver = undetected.Chrome(

  File "/usr/local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 316, in __init__

    super().__init__(options=options, service=service_)

  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__

    super().__init__(

  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__

    super().__init__(command_executor=executor, options=options)

  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__

    self.start_session(capabilities)

  File "/usr/local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 545, in start_session

    super().start_session(capabilities)

  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session

    response = self.execute(Command.NEW_SESSION, caps)["value"]

  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute

    self.error_handler.check_response(response)

  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response

    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:9222

from chrome not reachable```

**Comment by llewy** [comment]
Same error here

**Comment by calibrain** [comment]
Could you share your docker compose please ?

**Comment by TomasGalvao** [comment]
Sure thing:
```yaml
  books_downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: books_downloader
    networks:
      - backend
      - media
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: en
      USE_BOOK_TITLE: true
      FLASK_DEBUG: false
      TZ: Europe/London
      APP_ENV: prod
      UID: 1000
      GID: 1000
    restart: unless-stopped
    volumes:
      - <...>:/cwa-book-ingest # TODO: currently not the real path due to nfs chown error at entrypoint.sh
```
