### ISSUE TITLE
Reverse proxy setup?

### ISSUE THREAD

**Issue by shelldandy** [calibrain/calibre-web-automated-book-downloader#142]
Something changed between image `20250322` and current latest `20250416` that made the app not work with reverse proxies like traefik. Im not sure if this is something fixable with newer env variables perhaps? `localhost:8084` still works, its just the reverse proxy that doesn't

This is my config that works on `20250322` but not on `latest`

```yaml
bookdl:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:20250322
    container_name: bookdl
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      AA_DONATOR_KEY: ${AA_DONATOR_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/request/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      - ${MEDIA_SHARE}/media/books/cwa-book-ingest:/cwa-book-ingest
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CALIBRE_WEB_DL_SUBDOMAIN}.rule=Host(`${CALIBRE_WEB_DL_SUBDOMAIN}.bowline.im`)"
      - "traefik.http.services.${CALIBRE_WEB_DL_SUBDOMAIN}.loadbalancer.server.port=8084"
      - "traefik.http.routers.${CALIBRE_WEB_DL_SUBDOMAIN}.middlewares=tinyauth"
```

Thanks for the great app btw it really makes things easier :)

**Comment by calibrain** [comment]
Hey, it might just be the healthcheck that is broken now in latest
Could you try using the latest docker-compose ? https://github.com/calibrain/calibre-web-automated-book-downloader/blob/main/docker-compose.yml

I also removed dependency on CLOUDFLARE_PROXY_URL
Could you also try running in prod (new feature added) vs dev to see if thats the issue ?

**Comment by calibrain** [comment]
Could you share the entire docker-compose ? (feel free to **REDACT** anything private from there)
I will try to replicate the issue !

**Comment by mardijker** [comment]
Absolutely, here's the entire docker-compose.yml.

```
# If you change the FLASK_PORT, do not forget to change it in ports and healthcheck as well.
services:
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: calibredownloader
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: true
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      USE_BOOK_TITLE: true
      TZ: Asia/Bangkok
      APP_ENV: prod
      UID: 1000
      GID: 1000
    ports:
      - "10.20.20.0:8084:8084"
    expose:
      - 8084
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/request/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
    # This is where the booksdl will be downloaded to, usually it would be
    # the same as whatever you gave in "calibre-web-automated"
      - ~/docker/calibre-web-automated/calibre-web_ingress:/cwa-book-ingest
    networks:
      vpsinternal:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookdl.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.bookdl.entrypoints=https"
      - "traefik.http.services.bookdl.loadbalancer.server.port=8084"

networks:
  vpsinternal:
    external: true
```

If i were to give suggestion, that would be to add feature to log http request. That way, i think we can identify if the issue is in Calibre Book Downloader, misconfiguration in Traefik, or some magic stuffs that the Docker host do.
