### ISSUE TITLE
Correct Path Mapping Issue

### ISSUE THREAD

**Issue by necromancyr** [calibrain/calibre-web-automated-book-downloader#15]
So, I'm trying to map to the same directory that CWA is using (/mnt/user/media/books/import/) - see below for my compose.  Doesn't seem to be working correct.  Book downloads, is available, and I can actually grab it using the download link in CWA BD, but...it's not in /mnt/user/media/books/import (or imported by CWA and then deleted).  

```
# If you change the FLASK_PORT, do not forget to change it in ports and healthcheck as well.
services:
  calibre-web-automated-book-downloader:
    container_name: CWA-Downloader
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 9084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /mnt/user/media/books/import
      BOOK_LANGUAGE: en
    ports:
      - 9084:9084
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9084/request/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /mnt/user/media/books/import:${INGEST_DIR:-/cwa-book-ingest}

  cloudflarebypassforscraping:
    container_name: CWA-Downloader-CFBypass
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: unless-stopped
```

**Comment by calibrain** [comment]
Oh, this is my fault, I was mistaken in how docker compose works
Please keep the default value of Ingest dir and it should work
I will remove INGEST_DIR from the configuration on next release it does not make sense to be configurable, since its only used inside the docker and you can just mount it anywhere

Basically try this :

```
services:
  calibre-web-automated-book-downloader:
    container_name: CWA-Downloader
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 9084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
    ports:
      - 9084:9084
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9084/request/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /mnt/user/media/books/import:/cwa-book-ingest

  cloudflarebypassforscraping:
    container_name: CWA-Downloader-CFBypass
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: unless-stopped
   ```
