### ISSUE TITLE
[BUG] Every filetype is downloaded as epub

### ISSUE THREAD

**Issue by iLuckyW** [calibrain/calibre-web-automated-book-downloader#173]
## Bug Description
When downloading files, the extension of the downloaded file (when accessing through the cwa webui) is always .epub. Renaming the file with the correct extension, e. g. .pdf resolves the issues and the files can be used again.

## Steps To Reproduce
1. Select Book to download (no type .epub)
2. Wait for download to finish
3. Download by clicking on the title ot the book.

## Expected Behavior
The correct file extension should be used.

## Debug Information
This is part of my docker-compose.yaml

```
services:
  book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_DEBUG: 'false'
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      BOOK_LANGUAGE: en,de
      AA_BASE_URL: https://annas-archive.org
      SUPPORTED_FORMATS: pdf,epub,mobi,azw3,fb2,djvu,cbz,cbr
    volumes:
      - ${APPDATA_DIR}/book-downloader/books:/cwa-book-ingest
```
