### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by peel509-server** [calibrain/calibre-web-automated-book-downloader#180]
## Bug Description
LAtest version doesn't wanna start, mentionning /tmp is not writable

calibre-web-automated-book-downloader-1  | Starting entrypoint script
calibre-web-automated-book-downloader-1  | Log file: /var/log//cwa-book-downloader/cwa-bd_entrypoint.log
calibre-web-automated-book-downloader-1  | Build version: 2025-05-06-690c2b699ccdd60af9fb0f9e254379183dd74bac
calibre-web-automated-book-downloader-1  | Username for UID 0 is root
calibre-web-automated-book-downloader-1  | Changing ownership of /app to root:100
calibre-web-automated-book-downloader-1  | Changing ownership of /var/log/cwa-book-downloader to root:100
calibre-web-automated-book-downloader-1  | Changing ownership of /tmp/cwa-book-downloader to root:100
calibre-web-automated-book-downloader-1  | Test write to /cwa-book-ingest by root: true
calibre-web-automated-book-downloader-1  | Folder /cwa-book-ingest is writable, no need to change ownership
calibre-web-automated-book-downloader-1  | Test write to /cwa-book-ingest by root: true
calibre-web-automated-book-downloader-1  | Verifying /tmp has enough space
calibre-web-automated-book-downloader-1  | Failure: /tmp is not writable

## Steps To Reproduce
1. Had a properly functionning instance before pulling last version. 20250404 is working fine
2. Pulled Latest version and not working anymore

## Environment Information

- BASE OS: Ubuntu 22.04

## docker-compose
```
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      # CW users migrating should stop their existing CW instance, make a copy of the config folder, and bind that here to carry over all of their user settings ect.
      - /mnt/calibre/config:/config
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - /mnt/calibre/ingest:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - /mnt/calibre/library:/calibre-library
    ports:
      - 8083:8083
    restart: unless-stopped
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:20250413
    #    env_file: .env
    environment:
      UID: 1000
      GID: 1000
      TZ: Etc/UTC
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      APP_ENV: prod
      USE_BOOK_TITLE: true
      BOOK_LANGUAGE: en,fr
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      # This is where the books will be downloaded to, usually it would be 
      # the same as whatever you gave in "calibre-web-automated"
      - /mnt/calibre/ingest:/cwa-book-ingest
  cloudflarebypassforscraping:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: unless-stopped
```

## Additional Context
Added the UID/GID to the docker compose file, wasn't required on the last version to work
Tested multiple versions
