### ISSUE TITLE
Error when connected to VPN container's network

### ISSUE THREAD

**Issue by samcro1967** [calibrain/calibre-web-automated-book-downloader#20]
I have calibre-web-automated, calibre-web-automated-book-downloader, and cloudflarebypassforscraping all setup and running.  All of them are attached to a VPN container's network.  I am able to search for a book and queue it.  Cloudflare is successfully bypassed, but then I get the following error:

2024-12-22 16:02:18,981 - network - ERROR - Failed to download from :///get.php?md5=<redacted>&key=<redacted>: No connection adapters were found for ':///get.php?md5=<redacted>&key=<redacted>'

Any ideas?

**Comment by calibrain** [comment]
Hi @samcro1967 
This is a very weird error
Did you redact any part of it ? Or is this literally what is returned ?
Also, could you share your docker compose (please redact any personal information and tag it as `[redacted]` or something) ?
Also, are you using the `AA_DONATOR_KEY` ?

**Comment by samcro1967** [comment]
I did redact some of the log.  I did not realize GitHub stripped out what I redacted.  Should be better formatted below now.

```
2024-12-22 20:27:13,663 - network - ERROR - Failed to download from :///get.php?md5=<reacted>&key=<reacted>: No connection adapters were found for ':///get.php?md5=<reacted>&key=<reacted>'
```

I am not using AA_DONATOR_KEY.

I do not think it is a name resolution issue.  I can docker exec into the container, install ping, and ping google.com successfully.

Below is the Docker Compose.  Ports 8081:8083 and 8106:8106  are mapped and exposed on the wireguard-pia container.
```
  calibre-web-automated:
    container_name: calibre-web-automated
    image: crocodilestick/calibre-web-automated:latest
    restart: always
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
    volumes:
      - ${docker}/calibre-web-automated:/config
      - ${xbmc}/ebooks:/calibre-library
      - ${downloads}/cwa-book-ingest:/cwa-book-ingest
      #- /path/to/your/gmail/credentials.json:/app/calibre-web/gmail.json #Optional
    labels:
      - dockmap.service.port.int.0=8083
      - dockmap.service.port.ext.0=8081
    network_mode: service:wireguard-pia
    depends_on:
      - wireguard-pia
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: calibre-web-automated-book-downloader
    restart: always
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - FLASK_PORT=8106
      - PORT=8106
      - FLASK_DEBUG=false
      - CLOUDFLARE_PROXY_URL=http://localhost:8000
      - INGEST_DIR=/cwa-book-ingest
      - BOOK_LANGUAGE=en
    # ports:
      # - 9257:9257
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8106/request/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    volumes:
     - ${downloads}/cwa-book-ingest:${INGEST_DIR:-/cwa-book-ingest}
    labels:
      - dockmap.service.port.int.0=8106
      - dockmap.service.port.ext.0=8106
    network_mode: service:wireguard-pia
    depends_on:
      - wireguard-pia
  cloudflarebypassforscraping:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    container_name: cloudflarebypassforscraping
    restart: always
    network_mode: service:wireguard-pia
    depends_on:
      - wireguard-pia
```
