### ISSUE TITLE
Won't import book if ' in the title

### ISSUE THREAD

**Issue by chiefcastor** [calibrain/calibre-web-automated-book-downloader#29]
When downloading a book with an ' in the title it will not import. However, it will import if feed manually into Calibre Web Automated bypassing calibre-web-automated-book-downloader.

Seems like when it goes though calibre-web-automated-book-downloader it is failing to use the escape character on the ' when attempting to make the directory.   i.e using ' instead of \\' 

Calibre Web Automated logs show:

Traceback (most recent call last):

  File "calibre/db/cache.py", line 1857, in set_metadata

  File "calibre/db/cache.py", line 1780, in set_cover

  File "calibre/db/backend.py", line 1769, in set_cover

  File "os.py", line 225, in makedirs

**PermissionError: [Errno 13] Permission denied: "/calibre-library/Lev Grossman/The Magician's Land (384)"**

Traceback (most recent call last):

  File "runpy.py", line 198, in _run_module_as_main

  File "runpy.py", line 88, in _run_code

  File "site.py", line 47, in <module>

  File "site.py", line 43, in main

  File "calibre/db/cli/main.py", line 253, in main

  File "calibre/db/cli/main.py", line 40, in run_cmd

  File "calibre/db/cli/cmd_add.py", line 471, in main

  File "calibre/db/cli/cmd_add.py", line 236, in do_add

  File "calibre/db/cli/main.py", line 184, in run

  File "calibre/db/cli/cmd_add.py", line 177, in implementation

  File "calibre/db/cli/cmd_add.py", line 144, in book

  File "calibre/db/cli/cmd_add.py", line 96, in do_adding

  File "calibre/db/cli/cmd_add.py", line 53, in add_book

  File "calibre/db/cache.py", line 2194, in add_books

  File "calibre/db/cache.py", line 1979, in add_format

  File "calibre/db/cache.py", line 1935, in _do_add_format

  File "calibre/db/backend.py", line 1862, in add_format

  File "os.py", line 225, in makedirs

**PermissionError: [Errno 13] Permission denied: "/calibre-library/Lev Grossman/The Magician's Land (384)"**

**Comment by calibrain** [comment]
Hi ! 
Could you share your docker-compose ?
Also, which book are you trying to download ?
CWA-BD renames all books into `{MD5}.epub` so there should be no special characters
Also, it drops the books directly into the root of the folder, and does not create a sub directory

In your stack trace, it seems that some permission issues in your calibre-library folder
A 'hack' would be to just run `chmod 777 /calibre-library/` this might help
Or change to the proper ownership

**Comment by chiefcastor** [comment]
I tried changing ownership and it still failed. I am fairly positive it has to do with the ' in the title. 

These two books didn't import when downloaded with the downloader (I specifically tested 2 with ' in the title): 
```
The Magician's Land by Lev Grossman
I'm Starting to Worry about this Black Box of Doom by Jason Pargin
```

Other books download and import fine.

When I manually put them in the ingest folder they were imported just fine. So the issue is tied to the downloader.

I am not sure how the title is passed from the downloader to calibre/calibre-web-automated, but as you mentioned it clearly isn't coming form the {MD5}.epub. I assume the title is grabbed from the metadata and passed in then calibre tried to turn it into a directory. Where I get lost is trying to figure out how the downloader is different than manually putting it in the ingest folder. I am not a python expert, but I dig into the code a little bit to try to figure it out more.

This error from the calibre-web-automated logs:
`PermissionError: [Errno 13] Permission denied: "/calibre-library/Lev Grossman/The Magician's Land (384)"`
Based on the traceback from my first post it is failing to do a mkdir for this directory.

Docker compose 
```
services:
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      UID: 1000
      GID: 1000
    ports:
      - 8084:8084
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/request/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /downloads/completed/bookimport:${INGEST_DIR:-/cwa-book-ingest}

  cloudflarebypassforscraping:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: unless-stopped
```
